site_name: Documentacion Personal

nav:
  - Inicio: 'index.md'
  - Generar Documentacion Web: 'mkdocs.md'
  - Linux: 'linux.md'
  - Git : 'git.md'
  - Terminal Herramientas: 'Heramientas.md'

theme: readthedocs
